### ISSUE TITLE
Analyze Ads duplicating Occurrences.

### ISSUE THREAD

**Issue by sergi0aranda** [iQMedia/tracker#99]
I was testing the **Analyze Ads** and I noticed that when you click on the graph to see the ad schedule, it provides the occurrences duplicated at the same , in the same channel, program and market but attributed to a different Ad. I have included a screen below so you can see the issue. At first glance, it would seem that it is including deleted occurrences.
![Screenshot 2024-12-04 at 4 32 21 PM](https://github.com/user-attachments/assets/b65c0bd1-a2a5-412f-ba57-8f113260963b)
Below, you can see Teletrax and see that the issue is not present there.
![Screenshot 2024-12-04 at 5 01 06 PM](https://github.com/user-attachments/assets/d767f9e5-3ea9-4a74-bc8d-de7cdc9daaa0)

**Comment by jmylet** [comment]
These ads are not actually duplicating occurrences, even though they look like they are they have different client IDs, different creatives, different audiences, different media values, and even slightly different start times (though the UI doesn't display sub-second resolution). For example the first two walmart ads from your screenshot:
| Ad| ClientID| Creative| ClientHitID| StartDateTimeUtc|
|--------|--------|--------|--------|--------|
| Walmart v2024.44.00333| 17335| AE17335-2024-44-00333| 13938369868| 2024-11-30 06:00:51.057|
| Walmart v2024.44.03453| 16546| AE16546-2024-44-03453| 13938370090| 2024-11-30 06:00:51.127|

So from the solr ingestion perspective this is all completely valid and I'm guessing that the only reason these "duplicates" didn't show up in Teletrax is because you impersonated only the 16546 client when the analyze ads page is showing you both 16546 and 17335.

**Comment by sergi0aranda** [comment]
Thanks @jmylet . You are right. Sorry for sounding alarm when everything is normal. I will close the ticket.
